# Создать кастомные функции
# 1. Функция для расчета площади круга

DELIMITER //
CREATE FUNCTION CIRCLE_AREA(R NUMERIC(10,2))
RETURNS NUMERIC(10,3)
BEGIN 
	RETURN PI() * POW(R,2);
END //
DELIMITER ;

SELECT CIRCLE_AREA(3.5);
SELECT CIRCLE_AREA(10);

# 2. Функция для расчета гипотенузы треугольника

DELIMITER //
CREATE FUNCTION CALC_HYPOTENUSE(A NUMERIC(10,2), B NUMERIC(10,2))
RETURNS NUMERIC(10,4)
BEGIN
	RETURN SQRT(POW(A,2) + POW(B,2));
END //
DELIMITER ;

SELECT CALC_HYPOTENUSE(3, 4);
SELECT CALC_HYPOTENUSE(3.5, 14.7);

